version: "3.9"
services:
  mongodb:
    image: mongo:4.2.18
    container_name: mongodb
    ports:
      - "27017:27017"
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SPOTIFY_API_KEY=${SPOTIFY_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - JWT_KEY=${JWT_KEY}
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend
    depends_on:
      - backend
    ports:
      - "5000:5000"
